students_base/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('students_base_app.urls', namespace='students_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students_base_app/urls.py
from django.conf.urls import include, url

grouppatterns = [
    url(r'^(?P<group_id>\d+)/$', 'students_base_app.views.group_view', name='group_view'),
    url(r'^add/$', 'students_base_app.views.group_add', name='group_add'),
    url(r'^(?P<group_id>\d+)/edit/$', 'students_base_app.views.group_edit', name='group_edit'),
    url(r'^(?P<group_id>\d+)/delete/$', 'students_base_app.views.group_delete', name='group_delete'),
]

studentpatterns = [
    url(r'^add/$', 'students_base_app.views.student_add', name='student_add'),
    url(r'^(?P<student_id>\d+)/edit/$', 'students_base_app.views.student_edit', name='student_edit'),
    url(r'^(?P<student_id>\d+)/delete/$', 'students_base_app.views.student_delete', name='student_delete'),
]

accountpatterns = [
    url(r'^login/$', 'students_base_app.views.account_login', name='account_login'),
    url(r'^logout/$', 'students_base_app.views.account_logout', name='account_logout'),
]

urlpatterns = [
    url(r'^$', 'students_base_app.views.home', name='home'),
    url(r'^group/', include(grouppatterns)),
    url(r'^student/', include(studentpatterns)),
    url(r'^accounts/', include(accountpatterns)),
]

students_base_app/models.py
from django.db import models


# Create your models here.
class GroupManager(models.Manager):
    def get_queryset(self):
        return super(GroupManager, self).get_queryset().select_related('group_monitor').prefetch_related('student_set')


class Student(models.Model):
    full_name = models.CharField(max_length=75)
    photo = models.ImageField(upload_to='students')
    birthdate = models.DateField()
    studentid_cart = models.CharField(max_length=25, blank=True)
    group = models.ForeignKey(to='Group')

    def __unicode__(self):
        return self.full_name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.studentid_cart:
            try:
                student_id = self.id or (Student.objects.latest('id').id + 1)
            except Student.DoesNotExist:
                student_id = 1

            self.studentid_cart = u'{}-{}'.format(self.group.group_name, student_id)

        super(Student, self).save(force_insert, force_update, using, update_fields)


class Group(models.Model):
    group_name = models.CharField(max_length=25)
    group_monitor = models.ForeignKey(to=Student, related_name='+', blank=True, null=True, default=None)

    objects = GroupManager()

    def __unicode__(self):
        return self.group_name

    def get_group_monitor(self):
        return self.group_monitor.full_name if self.group_monitor else 'Group monitor not assigned.'

    get_group_monitor.short_description = 'Group monitor'

    def _students_count(self):
        return self.student_set.count()

    students_count = property(_students_count)

students_base_app/forms.py
from django import forms
from students_base_app.models import Student, Group


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['full_name', 'photo', 'birthdate', 'studentid_cart', 'group']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'birthdate': forms.TextInput(attrs={'class': 'form-control'}),
            'studentid_cart': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.Select(attrs={'class': 'form-control'}),
        }


class GroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        self.fields['group_monitor'].choices = Student.objects.filter(group=self.instance.id).values_list('id',
                                                                                                          'full_name')

    class Meta:
        model = Group
        fields = ['group_name', 'group_monitor']
        widgets = {
            'group_name': forms.TextInput(attrs={'class': 'form-control'}),
            'group_monitor': forms.Select(attrs={'class': 'form-control'}),
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

students_base_app/views.py
from django.views.generic import RedirectView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from students_base_app.models import Student, Group
from students_base_app.forms import StudentForm, GroupForm, LoginForm


# Create your views here.
class Home(ListView):
    template_name = 'students_base_app/home.html'
    model = Group
    context_object_name = 'groups'

home = login_required(Home.as_view())


class GroupView(DetailView):
    template_name = 'students_base_app/group/view.html'
    model = Group
    context_object_name = 'group'
    pk_url_kwarg = 'group_id'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(GroupView, self).get_context_data(**kwargs)

        paginator = Paginator(self.object.student_set.all(), self.paginate_by)
        page_obj = paginator.page(self.request.GET.get('page', 1))

        context['students'] = page_obj.object_list
        context['page_obj'] = page_obj

        return context

group_view = login_required(GroupView.as_view())


class GroupAdd(SuccessMessageMixin, CreateView):
    template_name = 'students_base_app/group/add.html'
    form_class = GroupForm
    success_url = reverse_lazy('students_app:home')
    success_message = 'New group was added.'

group_add = login_required(GroupAdd.as_view())


class GroupEdit(SuccessMessageMixin, UpdateView):
    template_name = 'students_base_app/group/edit.html'
    form_class = GroupForm
    model = Group
    pk_url_kwarg = 'group_id'
    context_object_name = 'group'
    success_message = 'Group was updated.'

    def get_success_url(self):
        return reverse('students_app:group_view', kwargs={'group_id': self.object.id})

group_edit = login_required(GroupEdit.as_view())


class GroupDelete(SuccessMessageMixin, DeleteView):
    template_name = 'students_base_app/delete_confirm.html'
    model = Group
    pk_url_kwarg = 'group_id'
    success_url = reverse_lazy('students_app:home')
    success_message = 'Group was deleted.'

group_delete = login_required(GroupDelete.as_view())


class StudentAdd(SuccessMessageMixin, CreateView):
    template_name = 'students_base_app/student/add.html'
    form_class = StudentForm
    success_message = 'New student was added.'

    def get_success_url(self):
        return reverse('students_app:group_view', kwargs={'group_id': self.object.group.id})

student_add = login_required(StudentAdd.as_view())


class StudentEdit(SuccessMessageMixin, UpdateView):
    template_name = 'students_base_app/student/edit.html'
    form_class = StudentForm
    model = Student
    pk_url_kwarg = 'student_id'
    success_message = 'Student profile updated.'

    def get_success_url(self):
        return reverse('students_app:group_view', kwargs={'group_id': self.object.group.id})

student_edit = login_required(StudentEdit.as_view())


class StudentDelete(SuccessMessageMixin, DeleteView):
    template_name = 'students_base_app/delete_confirm.html'
    model = Student
    pk_url_kwarg = 'student_id'
    success_message = 'Student was deleted.'

    def get_success_url(self):
        return reverse('students_app:group_view', kwargs={'group_id': self.object.group.id})

student_delete = login_required(StudentDelete.as_view())


class AccountLogin(SuccessMessageMixin, FormView):
    template_name = 'students_base_app/account/login.html'
    form_class = LoginForm
    success_message = 'You logged now.'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)

        if user and user.is_active:
            login(self.request, user)
        else:
            form.add_error('password', 'Login or password incorrect.')

            return super(AccountLogin, self).form_invalid(form)

        return super(AccountLogin, self).form_valid(form)

    def get_success_url(self):
        return self.request.GET.get('next', reverse('students_app:home'))

account_login = AccountLogin.as_view()


class AccountLogout(RedirectView):
    url = reverse_lazy('students_app:home')
    permanent = False

    def get(self, request, *args, **kwargs):
        logout(request)

        return super(AccountLogout, self).get(request, *args, **kwargs)

account_logout = login_required(AccountLogout.as_view())

students_base_app/templates/students_base_app/group/add.html
{% extends 'students_base_app/base.html' %}

{% block title %}Add group{% endblock %}

{% block page_title %}Add new group{% endblock %}

{% block content %}
    <form role="form" action="{% url 'students_app:group_add' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li class="text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-default">Save</button>
    </form>
{% endblock %}

students_base_app/templates/students_base_app/group/edit.html
{% extends 'students_base_app/base.html' %}

{% block title %}Edit group{% endblock %}

{% block page_title %}Edit group - {{ group }}{% endblock %}

{% block content %}
    <form role="form" action="{% url 'students_app:group_edit' group_id=group.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group {% if field.errors %}has-error{% endif %}">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li class="text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-default">Save changes</button>
        <a class="btn btn-danger pull-right" href="{% url 'students_app:group_delete' group_id=group.id %}">
            Delete group
        </a>
    </form>
{% endblock %}

students_base_app/templates/students_base_app/group/view.html
{% extends 'students_base_app/base.html' %}

{% load students_base_tags %}
{% load thumbnail %}

{% block title %}Group view{% endblock %}

{% block page_title %}View group - {{ group.group_name|upper }}{% endblock %}

{% block content %}
    <table class="table table-responsive table-bordered">
        <tr>
            <th>Photo</th>
            <th>Student</th>
            <th>Birthdate</th>
            <th>Student id</th>
            {% if request.user.is_staff %}
                <th>Admin edit link</th>
            {% endif %}
        </tr>
        {% for student in students %}
            <tr>
                <td>
                    {% thumbnail student.photo "100x100" crop="top" as img %}
                        <img src="{{ img.url }}" alt="{{ celebrity }}">
                    {% endthumbnail %}
                </td>
                <td><a href="{% url 'students_app:student_edit' student_id=student.id %}">{{ student }}</a></td>
                <td>{{ student.birthdate }}</td>
                <td>{{ student.studentid_cart }}</td>
                {% if request.user.is_staff %}
                    <td><a class="label label-default" href="{% edit student %}">edit</a></td>
                {% endif %}
            </tr>
        {% endfor %}
        <tr>
            <td colspan="{% if request.user.is_staff %}5{% else %}4{% endif %}">
                <a class="btn btn-info" href="{% url 'students_app:group_edit' group_id=group.id %}">Edit group</a>
            </td>
        </tr>
    </table>
    {% if page_obj.has_previous or page_obj.has_next %}
        <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="{{ home_url }}?page={{ page_obj.previous_page_number }}">&larr; Prev</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="{{ home_url }}?page={{ page_obj.next_page_number }}">Next &rarr;</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}